### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by martarodmo** [martarodmo/decont#1]
Hola Tomás,

Qué tal?

Quisiera preguntarte sobre la última task del ejercicio, no entiendo muy bien que hay que hacer:

**Create a log file with information on trimming and alignment results**

Muchas gracias.

Saludos.

**Comment by tdido** [comment]
Hola Marta.

Luego de ejecutar tu pipeline deberías tener un archivos de log de cutadapt (guardados en `log/cutadapt') y otros de star (guardados en out/star). Estos archivos contienen la información que pide el ejercicio. La idea es extraer la información de esos archivos y ponerla en un log general, o sea un archivo que crearías al finalizar el resto de los comandos de la pipeline. La idea es que cada vez que se ejecute la pipeline se añada la información debajo de lo anterior.
