### ISSUE TITLE
Entrega del examen

### ISSUE THREAD

**Issue by martarodmo** [martarodmo/decont#2]
Hola Tomás,
Acabo de subir la versión definitiva del examen a Git.

Saludos,
Marta.

**Comment by martarodmo** [comment]
_Aclaración_: Para que la salida se genere en el archivo "./log/pipeline.out" hay que ejecutar el script con el siguiente comando: 

**sh ./scripts/pipeline.sh  >  log/pipeline.out 2>&1**

**Comment by tdido** [comment]
Hola Marta. Está fenomenal, muy buen trabajo.
